runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app
service: mlab-api

runtime_config:
  python_version: 2

resources:
  cpu: 1.0
  memory_gb: 2.0
  disk_size_gb: 10

# health_check:
#   enable_health_check: false

#[START env]
env_variables:
    GOOGLE_APPLICATION_CREDENTIALS: "./cred.json"
#[END env]
