api_version: 1

runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app
service: data-api

threadsafe: true

runtime_config:
  python_version: 2

resources:
  cpu: 2.0
  memory_gb: 2.3
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 3
  max_num_instances: 13
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

# health_check:
#   enable_health_check: false

# Environment variables are set by the ./deploy.sh script
env_variables:
    GOOGLE_APPLICATION_CREDENTIALS: "{{GOOGLE_APPLICATION_CREDENTIALS}}"
    API_MODE: "{{API_MODE}}"
    PROJECT: "{{PROJECT}}"
    BIGTABLE_INSTANCE: "{{BIGTABLE_INSTANCE}}"
    BIGTABLE_CONFIG_DIR: "{{BIGTABLE_CONFIG_DIR}}"
    BIGTABLE_POOL_SIZE: "{{BIGTABLE_POOL_SIZE}}"
